

services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb+srv://tranchinht32901:nut6xEcbdYwdfDWl@invoice.eu9gjhs.mongodb.net/?retryWrites=true&w=majority&appName=invoice
    networks:
      - app-network

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      - VITE_API=http://localhost:3000
      # - VITE_API=http://backend:3000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge